saas/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # 路由分发
    url(r'^app01/', include('app01.urls', namespace='app01')),
    # 不加前缀就解析到web
    url(r'^', include('web.urls')),
]

web/urls.py
from django.conf.urls import url, include
from web.views import home

from web.views import account

urlpatterns = [
    # 加上name属性方便反向解析
    url(r'^register/$', account.register, name='register'),
    url(r'^send/sms/$', account.send_sms, name='send_sms'),
    url(r'^login/sms/$', account.login_sms, name='login_sms'),
    url(r'^login/$', account.login, name='login'),
    url(r'^image/code/$', account.image_code, name='image_code'),
    url(r'^index/$', home.index, name='index'),
    url(r'^logout/$', account.logout, name='logout'),

]

web/models.py
from django.db import models


# Create your models here.
class UserInfo(models.Model):
    # ORM在为我们创建数据库的时候可以为该字段创建索引 查询的时候比较快
    username = models.CharField(verbose_name="用户名", max_length=32, db_index=True)
    email = models.EmailField(verbose_name="邮箱", max_length=32)
    phone = models.CharField(verbose_name="手机号", max_length=32)
    password = models.CharField(verbose_name="密码", max_length=32)


class PricePolicy(models.Model):
    # 价格策略
    category_choices = (
        (1, '免费版'),
        (2, '收费版'),
        (3, '其他'),
    )
    category = models.SmallIntegerField(verbose_name='收费类型', default=1, choices=category_choices)  # 数据库中为smallint类型
    title = models.CharField(verbose_name='标题', max_length=32)
    price = models.PositiveIntegerField(verbose_name='价格')
    project_num = models.PositiveIntegerField(verbose_name='项目数')
    project_member = models.PositiveIntegerField(verbose_name='成员数')
    project_size = models.PositiveIntegerField(verbose_name='项目空间')
    pre_file_size = models.PositiveIntegerField(verbose_name='单文件大小')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Transaction(models.Model):
    """交易记录"""
    status_choice = (
        (1, '未支付'),
        (2, '已支付'),
        (3, '已取消'),
    )
    status = models.SmallIntegerField(verbose_name='交易状态', choices=status_choice)
    order = models.CharField(verbose_name='订单号', max_length=64, unique=True)  # 唯一索引 查询的时候速度最快 值不能重复
    user = models.ForeignKey(verbose_name='用户', to='UserInfo')
    price_policy = models.ForeignKey(verbose_name='价格策略', to='PricePolicy' )
    count = models.IntegerField(verbose_name='数量（年）', help_text='0表示无限制')
    price = models.IntegerField(verbose_name='支付价格')
    start_datetime = models.DateTimeField(verbose_name='开始时间', null=True, blank=True)  # 默认为空
    end_datetime = models.DateTimeField(verbose_name='结束时间', null=True, blank=True)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class Project(models.Model):
    color_choices = (
        (1, '#56b8eb'),
        (2, '#f28033'),
    )
    name = models.CharField(verbose_name='任务名', max_length=32)
    color = models.SmallIntegerField(verbose_name='颜色', choices=color_choices, default=1)
    desc = models.CharField(verbose_name='项目描述', max_length=255, null=True, blank=True)
    use_space = models.IntegerField('项目已用空间', default=0)
    star = models.BooleanField('星标', default=False)
    # bucket = models.CharField(verbose_name='对象存储桶', max_length=128)
    # region = models.CharField(verbose_name='对象存储区域', max_length=32)
    join_count = models.SmallIntegerField(verbose_name='参与人数', default=1)
    creator = models.ForeignKey(verbose_name='创建者', to='UserInfo')
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)


class ProjectParticipants(models.Model):
    user = models.ForeignKey(verbose_name='项目参与者', to='UserInfo')
    project = models.ForeignKey(verbose_name='项目', to='Project')
    star = models.BooleanField(verbose_name='星标', default=False)
    create_datetime = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

web/templates/web/index.html
{% extends 'layout/basic.html' %}
{% load static %}
{% block title %}首页{% endblock %}

{% block css %}
    <style>
        img{
            width: 100%;

        }
    </style>
{% endblock %}

{% block contant %}
    <div>
        <img src="{% static 'web/img/index/index.png' %}" alt="">
    </div>
{% endblock %}

web/templates/web/login.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
{% endblock %}

{% block title %}用户登录{% endblock %}

{% block contant %}
    <div class="container account">
        <div class="title">用户登陆</div>
{#  不对表单数据校验  #}
{#    这里用form表单不用ajax是为了提交的时候页面自动刷新 验证码也可以随之刷新   #}
        <form id="smsForm" method="post" action="" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-5">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>
                        <div class="col-sm-4 d-grid div-code">
                            <img src="{% url 'image_code' %}" id="imgCode" title="点击更换验证码">
                        </div>
                    </div>
                {% else %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>

                    </div>
                {% endif %}
            {% endfor %}
{#            <div>#}
{#                <div style="float: right">#}
{#                    <a href="{% url 'login_sms' %}">短信登陆</a>#}
{#                </div>#}
{#            </div>#}
            <div class="d-grid gap-2">
            {#不能写submit类型否则会跳转到新界面 因为要通过ajax提交  不影响倒计时#}
                <div class="input-group">
                    <input id="btnLogin"  value="登录" type="submit" class="btn btn-primary form-control">
{#                  <button type="button" class="btn btn-outline-secondary dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">#}
{#                    <span class="visually-hidden">Toggle Dropdown</span>#}
{#                  </button>#}
{#                  <ul class="dropdown-menu dropdown-menu-end">#}
{#                    <li><a class="dropdown-item" href="{% url 'login_sms' %}">短信登录</a></li>#}
{#                  </ul>#}
                </div>


                <input value="新用户注册" type="button" class="btn btn-outline-primary" onclick="window.location.href='/register/'">
            </div>
            <div style="margin-top: 5px">
                <a href="{% url 'login_sms' %}" style="text-decoration-line: none">手机短信登录</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function (){
            bindClickBtnImgCode()
        })
        function bindClickBtnImgCode(){
            $('#imgCode').click(function (){
                let oldSrc = $(this).attr('src')
                $(this).attr('src', oldSrc + '?')
            })
        }
    </script>
{% endblock %}

web/templates/web/login_sms.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
{% endblock %}

{% block title %}用户登录{% endblock %}

{% block contant %}
    <div class="container account">
        <div class="title">用户登陆</div>
{#  不对表单数据校验  #}
        <form id="smsForm" method="post" action="" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-5">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>
                        <div class="col-sm-4 d-grid div-code">
                            <input id="btnSms" type="button" class="btn btn-secondary btn-code" value="发送验证码"/>
                        </div>
                    </div>
                {% else %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>

                    </div>
                {% endif %}
            {% endfor %}

            <div class="d-grid gap-2">
            {#不能写submit类型否则会跳转到新界面 因为要通过ajax提交  不影响倒计时#}
                <input id="btnLogin" value="登录" type="button" class="btn btn-primary">
                <input value="新用户注册" type="button" class="btn btn-outline-primary" onclick="window.location.href='/register/'">
            </div>
            <div style="margin-top: 5px">
                <a href="{% url 'login' %}" style="text-decoration-line: none">账户密码登录</a>
            </div>
        </form>
    </div>
{% endblock %}

{% block js %}
    <script>
        $(function(){
            bindClickBtnSms()
            bindClickBtnLogin()
        });
        function bindClickBtnSms(){
            $('#btnSms').click(function (){
                {#将所有错误信息置为空#}
                $('.error-msg').empty()
                {#获取csrf_token#}
                const regex = /.*csrftoken=([^;.]*).*$/;
                let xCSRFToken = document.cookie.match(regex) === null ? null : document.cookie.match(regex)[1]

                let phone = $('#id_phone').val();
                {#发送ajax请求，将手机号发送到后台#}
                $.ajax({
                    url:"{% url 'send_sms' %}",
                    type:"POST",
                    data:{
                        phone:phone,
                        tpl:"login"
                    },
                    {#将服务端返回的数据反序列化为字典#}
                    dataType:"JSON",
                    headers: {
                        "X-CSRFToken": xCSRFToken
                    },
                    {#ajax请求发送成功后自动回调,res就是后段返回到值#}
                    success:function (res){
                        console.log(res);
                        {#如果后段返回成功#}
                        if(res.status){
                            sendSmsDelay()
                            console.log('发送成功');
                        }else{
                            $.each(res.error, function (k,v){
                                {#找到当前元素的下一个元素（即对应的错误信息span）并添加错误信息#}
                                console.log(v[0]);
                                $("#id_"+k).next().text(v[0]);
                            })
                        }
                    }
                })
            })
        }
        {#倒计时#}
        function sendSmsDelay(){
            let $smsBtn = $("#btnSms")

            $smsBtn.prop('disabled',true)
            let time = 60
            let remind = setInterval(function (){
                $smsBtn.val('重新发送('+time+'s)')
                time = time - 1
                if (time < 1){
                    clearInterval(remind)
                    $smsBtn.val('重新发送').prop('disabled', false)
                }
            }, 1000)
        }

        function bindClickBtnLogin() {
            $('#btnLogin').click(function (){
                $('.error-msg').empty()
                {#收集表单中的数据#}
                {#ajax发送到后台#}
                {#获取到表单的所有键值，还能携带CSRF_Token#}
                let data = $('#smsForm').serialize()
                console.log(data)
                $.ajax({
                    data: data,
                    type: 'POST',
                    url: '{% url 'login_sms' %}',
                    dataType: "JSON",
                    success:function (res){
                        console.log(res)
                        if(res.status){
                            console.log('注册成功');
                            location.href = res.data
                        }else{
                            $.each(res.error, function (k,v){
                                {#找到当前元素的下一个元素（即对应的错误信息span）并添加错误信息#}
                                console.log(v[0]);
                                $("#id_"+k).next().text(v[0]);
                            })
                        }
                    },
                })
            })
        }
    </script>
{% endblock %}

web/templates/web/register.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'web/css/account.css' %}">
{% endblock %}

{% block title %}用户注册{% endblock %}

{% block contant %}
    <div class="container account">
        <div class="title">用户注册</div>
{#  不对表单数据校验  #}
        <form id="regForm" method="post" action="" novalidate>
            {% csrf_token %}
            {% for field in form %}
                {% if field.name == 'code' %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-5">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>
                        <div class="col-sm-4 d-grid div-code">
                            <input id="btnSms" type="button" class="btn btn-secondary btn-code" value="发送验证码"/>
                        </div>
                    </div>
                {% else %}
                    <div class="row  form-group">
                        <label for="{{ field.id_for_label }}" class="col-sm-3 col-form-label">{{ field.label }}</label>
                        <div class="col-sm-9">
                            {{ field }}
                            <span class="error-msg">{{ field.errors.0 }}</span>
                        </div>

                    </div>
                {% endif %}
            {% endfor %}

            <div class="d-grid gap-2">
{#不能写submit类型 因为要通过ajax提交 不影响倒计时#}
                <input id="btnReg" value="注册" type="button" class="btn btn-primary">
                <input value="返回登陆" type="button" class="btn btn-outline-primary" onclick="window.location.href='/login/'">
            </div>
        </form>
    </div>


{% endblock %}

{% block js %}
{#  页面加载完成后自动执行  #}
    <script>
        function bindClickBtnReg() {
            $('#btnReg').click(function (){
                $('.error-msg').empty()
                {#收集表单中的数据#}
                {#ajax发送到后台#}
                {#获取到表单的所有键值，还能携带CSRFToken#}
                let data = $('#regForm').serialize()
                $.ajax({
                    data: data,
                    type: 'POST',
                    url: '{% url 'register' %}',
                    dataType: "JSON",
                    success:function (res){
                        console.log(res)
                        if(res.status){
                            console.log('注册成功');
                            location.href = res.data
                        }else{
                            $.each(res.error, function (k,v){
                                {#找到当前元素的下一个元素（即对应的错误信息span）并添加错误信息#}
                                console.log(v[0]);
                                $("#id_"+k).next().text(v[0]);
                            })
                        }
                    },
                })
            })
        }

        $(function(){
            bindClickBtnSms()
            bindClickBtnReg()
        });
        {#点击获取验证码的按钮绑定事件#}
        function bindClickBtnSms(){
            $('#btnSms').click(function (){
                {#将所有错误信息置为空#}
                $('.error-msg').empty()
                {#获取csrf_token#}
                const regex = /.*csrftoken=([^;.]*).*$/;
                let xCSRFToken = document.cookie.match(regex) === null ? null : document.cookie.match(regex)[1]

                let phone = $('#id_phone').val();
                {#发送ajax请求，将手机号发送到后台#}
                $.ajax({
                    url:"{% url 'send_sms' %}",
                    type:"POST",
                    data:{
                        phone:phone,
                        tpl:"register"
                    },
                    {#将服务端返回的数据反序列化为字典#}
                    dataType:"JSON",
                    headers: {
                        "X-CSRFToken": xCSRFToken
                    },
                    {#ajax请求发送成功后自动回调,res就是后段返回到值#}
                    success:function (res){
                        console.log(res);
                        {#如果后段返回成功#}
                        if(res.status){
                            sendSmsDelay()
                            console.log('发送成功');
                        }else{
                            $.each(res.error, function (k,v){
                                {#找到当前元素的下一个元素（即对应的错误信息span）并添加错误信息#}
                                console.log(v[0]);
                                $("#id_"+k).next().text(v[0]);
                            })
                        }
                    }
                })
            })
        }
        {#倒计时#}
        function sendSmsDelay(){
            let $smsBtn = $("#btnSms")

            $smsBtn.prop('disabled',true)
            let time = 60
            let remind = setInterval(function (){
                $smsBtn.val('重新发送('+time+'s)')
                time = time - 1
                if (time < 1){
                    clearInterval(remind)
                    $smsBtn.val('重新发送').prop('disabled', false)
                }
            }, 1000)
        }
    </script>
{% endblock %}